/*
RAG Defender Unified Gateway

Testing SAMIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sami_rag_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	samiclient "github.com/Autnhive-Devsecops-Org/sami-sdk-go"
)

func Test_sami_rag_client_SAMIAPIService(t *testing.T) {

	configuration := samiclient.NewConfiguration()
	apiClient := samiclient.NewAPIClient(configuration)

	t.Run("Test SAMIAPIService ApproveQuarantineDoc", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var docId string

		resp, httpRes, err := apiClient.SAMIAPI.ApproveQuarantineDoc(context.Background(), docId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SAMIAPIService IngestCommit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SAMIAPI.IngestCommit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SAMIAPIService IngestSync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SAMIAPI.IngestSync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SAMIAPIService RejectQuarantineDoc", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var docId string

		resp, httpRes, err := apiClient.SAMIAPI.RejectQuarantineDoc(context.Background(), docId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
