/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PolicyEnforcementSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyEnforcementSummary{}

// PolicyEnforcementSummary struct for PolicyEnforcementSummary
type PolicyEnforcementSummary struct {
	PolicyMode string `json:"policy_mode"`
	Blocked bool `json:"blocked"`
	Reason NullableString `json:"reason"`
	RetrieverBackend NullableString `json:"retriever_backend,omitempty"`
	LegacyBackfillRequired *bool `json:"legacy_backfill_required,omitempty"`
	LegacyBackfillCompleted *bool `json:"legacy_backfill_completed,omitempty"`
	RiskAcknowledgedAt NullableString `json:"risk_acknowledged_at,omitempty"`
}

type _PolicyEnforcementSummary PolicyEnforcementSummary

// NewPolicyEnforcementSummary instantiates a new PolicyEnforcementSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyEnforcementSummary(policyMode string, blocked bool, reason NullableString) *PolicyEnforcementSummary {
	this := PolicyEnforcementSummary{}
	this.PolicyMode = policyMode
	this.Blocked = blocked
	this.Reason = reason
	var legacyBackfillRequired bool = true
	this.LegacyBackfillRequired = &legacyBackfillRequired
	var legacyBackfillCompleted bool = false
	this.LegacyBackfillCompleted = &legacyBackfillCompleted
	return &this
}

// NewPolicyEnforcementSummaryWithDefaults instantiates a new PolicyEnforcementSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyEnforcementSummaryWithDefaults() *PolicyEnforcementSummary {
	this := PolicyEnforcementSummary{}
	var legacyBackfillRequired bool = true
	this.LegacyBackfillRequired = &legacyBackfillRequired
	var legacyBackfillCompleted bool = false
	this.LegacyBackfillCompleted = &legacyBackfillCompleted
	return &this
}

// GetPolicyMode returns the PolicyMode field value
func (o *PolicyEnforcementSummary) GetPolicyMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyMode
}

// GetPolicyModeOk returns a tuple with the PolicyMode field value
// and a boolean to check if the value has been set.
func (o *PolicyEnforcementSummary) GetPolicyModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyMode, true
}

// SetPolicyMode sets field value
func (o *PolicyEnforcementSummary) SetPolicyMode(v string) {
	o.PolicyMode = v
}

// GetBlocked returns the Blocked field value
func (o *PolicyEnforcementSummary) GetBlocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value
// and a boolean to check if the value has been set.
func (o *PolicyEnforcementSummary) GetBlockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Blocked, true
}

// SetBlocked sets field value
func (o *PolicyEnforcementSummary) SetBlocked(v bool) {
	o.Blocked = v
}

// GetReason returns the Reason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PolicyEnforcementSummary) GetReason() string {
	if o == nil || o.Reason.Get() == nil {
		var ret string
		return ret
	}

	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyEnforcementSummary) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// SetReason sets field value
func (o *PolicyEnforcementSummary) SetReason(v string) {
	o.Reason.Set(&v)
}

// GetRetrieverBackend returns the RetrieverBackend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyEnforcementSummary) GetRetrieverBackend() string {
	if o == nil || IsNil(o.RetrieverBackend.Get()) {
		var ret string
		return ret
	}
	return *o.RetrieverBackend.Get()
}

// GetRetrieverBackendOk returns a tuple with the RetrieverBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyEnforcementSummary) GetRetrieverBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetrieverBackend.Get(), o.RetrieverBackend.IsSet()
}

// HasRetrieverBackend returns a boolean if a field has been set.
func (o *PolicyEnforcementSummary) HasRetrieverBackend() bool {
	if o != nil && o.RetrieverBackend.IsSet() {
		return true
	}

	return false
}

// SetRetrieverBackend gets a reference to the given NullableString and assigns it to the RetrieverBackend field.
func (o *PolicyEnforcementSummary) SetRetrieverBackend(v string) {
	o.RetrieverBackend.Set(&v)
}
// SetRetrieverBackendNil sets the value for RetrieverBackend to be an explicit nil
func (o *PolicyEnforcementSummary) SetRetrieverBackendNil() {
	o.RetrieverBackend.Set(nil)
}

// UnsetRetrieverBackend ensures that no value is present for RetrieverBackend, not even an explicit nil
func (o *PolicyEnforcementSummary) UnsetRetrieverBackend() {
	o.RetrieverBackend.Unset()
}

// GetLegacyBackfillRequired returns the LegacyBackfillRequired field value if set, zero value otherwise.
func (o *PolicyEnforcementSummary) GetLegacyBackfillRequired() bool {
	if o == nil || IsNil(o.LegacyBackfillRequired) {
		var ret bool
		return ret
	}
	return *o.LegacyBackfillRequired
}

// GetLegacyBackfillRequiredOk returns a tuple with the LegacyBackfillRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyEnforcementSummary) GetLegacyBackfillRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.LegacyBackfillRequired) {
		return nil, false
	}
	return o.LegacyBackfillRequired, true
}

// HasLegacyBackfillRequired returns a boolean if a field has been set.
func (o *PolicyEnforcementSummary) HasLegacyBackfillRequired() bool {
	if o != nil && !IsNil(o.LegacyBackfillRequired) {
		return true
	}

	return false
}

// SetLegacyBackfillRequired gets a reference to the given bool and assigns it to the LegacyBackfillRequired field.
func (o *PolicyEnforcementSummary) SetLegacyBackfillRequired(v bool) {
	o.LegacyBackfillRequired = &v
}

// GetLegacyBackfillCompleted returns the LegacyBackfillCompleted field value if set, zero value otherwise.
func (o *PolicyEnforcementSummary) GetLegacyBackfillCompleted() bool {
	if o == nil || IsNil(o.LegacyBackfillCompleted) {
		var ret bool
		return ret
	}
	return *o.LegacyBackfillCompleted
}

// GetLegacyBackfillCompletedOk returns a tuple with the LegacyBackfillCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyEnforcementSummary) GetLegacyBackfillCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.LegacyBackfillCompleted) {
		return nil, false
	}
	return o.LegacyBackfillCompleted, true
}

// HasLegacyBackfillCompleted returns a boolean if a field has been set.
func (o *PolicyEnforcementSummary) HasLegacyBackfillCompleted() bool {
	if o != nil && !IsNil(o.LegacyBackfillCompleted) {
		return true
	}

	return false
}

// SetLegacyBackfillCompleted gets a reference to the given bool and assigns it to the LegacyBackfillCompleted field.
func (o *PolicyEnforcementSummary) SetLegacyBackfillCompleted(v bool) {
	o.LegacyBackfillCompleted = &v
}

// GetRiskAcknowledgedAt returns the RiskAcknowledgedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PolicyEnforcementSummary) GetRiskAcknowledgedAt() string {
	if o == nil || IsNil(o.RiskAcknowledgedAt.Get()) {
		var ret string
		return ret
	}
	return *o.RiskAcknowledgedAt.Get()
}

// GetRiskAcknowledgedAtOk returns a tuple with the RiskAcknowledgedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PolicyEnforcementSummary) GetRiskAcknowledgedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskAcknowledgedAt.Get(), o.RiskAcknowledgedAt.IsSet()
}

// HasRiskAcknowledgedAt returns a boolean if a field has been set.
func (o *PolicyEnforcementSummary) HasRiskAcknowledgedAt() bool {
	if o != nil && o.RiskAcknowledgedAt.IsSet() {
		return true
	}

	return false
}

// SetRiskAcknowledgedAt gets a reference to the given NullableString and assigns it to the RiskAcknowledgedAt field.
func (o *PolicyEnforcementSummary) SetRiskAcknowledgedAt(v string) {
	o.RiskAcknowledgedAt.Set(&v)
}
// SetRiskAcknowledgedAtNil sets the value for RiskAcknowledgedAt to be an explicit nil
func (o *PolicyEnforcementSummary) SetRiskAcknowledgedAtNil() {
	o.RiskAcknowledgedAt.Set(nil)
}

// UnsetRiskAcknowledgedAt ensures that no value is present for RiskAcknowledgedAt, not even an explicit nil
func (o *PolicyEnforcementSummary) UnsetRiskAcknowledgedAt() {
	o.RiskAcknowledgedAt.Unset()
}

func (o PolicyEnforcementSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyEnforcementSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy_mode"] = o.PolicyMode
	toSerialize["blocked"] = o.Blocked
	toSerialize["reason"] = o.Reason.Get()
	if o.RetrieverBackend.IsSet() {
		toSerialize["retriever_backend"] = o.RetrieverBackend.Get()
	}
	if !IsNil(o.LegacyBackfillRequired) {
		toSerialize["legacy_backfill_required"] = o.LegacyBackfillRequired
	}
	if !IsNil(o.LegacyBackfillCompleted) {
		toSerialize["legacy_backfill_completed"] = o.LegacyBackfillCompleted
	}
	if o.RiskAcknowledgedAt.IsSet() {
		toSerialize["risk_acknowledged_at"] = o.RiskAcknowledgedAt.Get()
	}
	return toSerialize, nil
}

func (o *PolicyEnforcementSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy_mode",
		"blocked",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyEnforcementSummary := _PolicyEnforcementSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyEnforcementSummary)

	if err != nil {
		return err
	}

	*o = PolicyEnforcementSummary(varPolicyEnforcementSummary)

	return err
}

type NullablePolicyEnforcementSummary struct {
	value *PolicyEnforcementSummary
	isSet bool
}

func (v NullablePolicyEnforcementSummary) Get() *PolicyEnforcementSummary {
	return v.value
}

func (v *NullablePolicyEnforcementSummary) Set(val *PolicyEnforcementSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyEnforcementSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyEnforcementSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyEnforcementSummary(val *PolicyEnforcementSummary) *NullablePolicyEnforcementSummary {
	return &NullablePolicyEnforcementSummary{value: val, isSet: true}
}

func (v NullablePolicyEnforcementSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyEnforcementSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


