/*
Enterprise Connection Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_firewall_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatCompletionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionRequest{}

// ChatCompletionRequest struct for ChatCompletionRequest
type ChatCompletionRequest struct {
	// List of messages comprising the conversation.
	Messages []ChatMessage `json:"messages"`
	// Optional explicit OpenAI API key.
	AI_KEY NullableString `json:"AI_KEY,omitempty"`
	// Optional custom provider base URL.
	AI_URL NullableString `json:"AI_URL,omitempty"`
	// Optional provider routing string.
	AI_PROVIDER NullableString `json:"AI_PROVIDER,omitempty"`
}

type _ChatCompletionRequest ChatCompletionRequest

// NewChatCompletionRequest instantiates a new ChatCompletionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionRequest(messages []ChatMessage) *ChatCompletionRequest {
	this := ChatCompletionRequest{}
	this.Messages = messages
	return &this
}

// NewChatCompletionRequestWithDefaults instantiates a new ChatCompletionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionRequestWithDefaults() *ChatCompletionRequest {
	this := ChatCompletionRequest{}
	return &this
}

// GetMessages returns the Messages field value
func (o *ChatCompletionRequest) GetMessages() []ChatMessage {
	if o == nil {
		var ret []ChatMessage
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionRequest) GetMessagesOk() ([]ChatMessage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *ChatCompletionRequest) SetMessages(v []ChatMessage) {
	o.Messages = v
}

// GetAI_KEY returns the AI_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionRequest) GetAI_KEY() string {
	if o == nil || IsNil(o.AI_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.AI_KEY.Get()
}

// GetAI_KEYOk returns a tuple with the AI_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionRequest) GetAI_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AI_KEY.Get(), o.AI_KEY.IsSet()
}

// HasAI_KEY returns a boolean if a field has been set.
func (o *ChatCompletionRequest) HasAI_KEY() bool {
	if o != nil && o.AI_KEY.IsSet() {
		return true
	}

	return false
}

// SetAI_KEY gets a reference to the given NullableString and assigns it to the AI_KEY field.
func (o *ChatCompletionRequest) SetAI_KEY(v string) {
	o.AI_KEY.Set(&v)
}
// SetAI_KEYNil sets the value for AI_KEY to be an explicit nil
func (o *ChatCompletionRequest) SetAI_KEYNil() {
	o.AI_KEY.Set(nil)
}

// UnsetAI_KEY ensures that no value is present for AI_KEY, not even an explicit nil
func (o *ChatCompletionRequest) UnsetAI_KEY() {
	o.AI_KEY.Unset()
}

// GetAI_URL returns the AI_URL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionRequest) GetAI_URL() string {
	if o == nil || IsNil(o.AI_URL.Get()) {
		var ret string
		return ret
	}
	return *o.AI_URL.Get()
}

// GetAI_URLOk returns a tuple with the AI_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionRequest) GetAI_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AI_URL.Get(), o.AI_URL.IsSet()
}

// HasAI_URL returns a boolean if a field has been set.
func (o *ChatCompletionRequest) HasAI_URL() bool {
	if o != nil && o.AI_URL.IsSet() {
		return true
	}

	return false
}

// SetAI_URL gets a reference to the given NullableString and assigns it to the AI_URL field.
func (o *ChatCompletionRequest) SetAI_URL(v string) {
	o.AI_URL.Set(&v)
}
// SetAI_URLNil sets the value for AI_URL to be an explicit nil
func (o *ChatCompletionRequest) SetAI_URLNil() {
	o.AI_URL.Set(nil)
}

// UnsetAI_URL ensures that no value is present for AI_URL, not even an explicit nil
func (o *ChatCompletionRequest) UnsetAI_URL() {
	o.AI_URL.Unset()
}

// GetAI_PROVIDER returns the AI_PROVIDER field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionRequest) GetAI_PROVIDER() string {
	if o == nil || IsNil(o.AI_PROVIDER.Get()) {
		var ret string
		return ret
	}
	return *o.AI_PROVIDER.Get()
}

// GetAI_PROVIDEROk returns a tuple with the AI_PROVIDER field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionRequest) GetAI_PROVIDEROk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AI_PROVIDER.Get(), o.AI_PROVIDER.IsSet()
}

// HasAI_PROVIDER returns a boolean if a field has been set.
func (o *ChatCompletionRequest) HasAI_PROVIDER() bool {
	if o != nil && o.AI_PROVIDER.IsSet() {
		return true
	}

	return false
}

// SetAI_PROVIDER gets a reference to the given NullableString and assigns it to the AI_PROVIDER field.
func (o *ChatCompletionRequest) SetAI_PROVIDER(v string) {
	o.AI_PROVIDER.Set(&v)
}
// SetAI_PROVIDERNil sets the value for AI_PROVIDER to be an explicit nil
func (o *ChatCompletionRequest) SetAI_PROVIDERNil() {
	o.AI_PROVIDER.Set(nil)
}

// UnsetAI_PROVIDER ensures that no value is present for AI_PROVIDER, not even an explicit nil
func (o *ChatCompletionRequest) UnsetAI_PROVIDER() {
	o.AI_PROVIDER.Unset()
}

func (o ChatCompletionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages
	if o.AI_KEY.IsSet() {
		toSerialize["AI_KEY"] = o.AI_KEY.Get()
	}
	if o.AI_URL.IsSet() {
		toSerialize["AI_URL"] = o.AI_URL.Get()
	}
	if o.AI_PROVIDER.IsSet() {
		toSerialize["AI_PROVIDER"] = o.AI_PROVIDER.Get()
	}
	return toSerialize, nil
}

func (o *ChatCompletionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatCompletionRequest := _ChatCompletionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatCompletionRequest)

	if err != nil {
		return err
	}

	*o = ChatCompletionRequest(varChatCompletionRequest)

	return err
}

type NullableChatCompletionRequest struct {
	value *ChatCompletionRequest
	isSet bool
}

func (v NullableChatCompletionRequest) Get() *ChatCompletionRequest {
	return v.value
}

func (v *NullableChatCompletionRequest) Set(val *ChatCompletionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionRequest(val *ChatCompletionRequest) *NullableChatCompletionRequest {
	return &NullableChatCompletionRequest{value: val, isSet: true}
}

func (v NullableChatCompletionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


