/*
Enterprise Connection Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_firewall_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignedUrlPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignedUrlPayload{}

// SignedUrlPayload Request body for signed URL batch processing.  Attributes:     jobs            (List[Job]):      List of signed URL jobs.
type SignedUrlPayload struct {
	Jobs []Job `json:"jobs"`
}

type _SignedUrlPayload SignedUrlPayload

// NewSignedUrlPayload instantiates a new SignedUrlPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignedUrlPayload(jobs []Job) *SignedUrlPayload {
	this := SignedUrlPayload{}
	this.Jobs = jobs
	return &this
}

// NewSignedUrlPayloadWithDefaults instantiates a new SignedUrlPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignedUrlPayloadWithDefaults() *SignedUrlPayload {
	this := SignedUrlPayload{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *SignedUrlPayload) GetJobs() []Job {
	if o == nil {
		var ret []Job
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *SignedUrlPayload) GetJobsOk() ([]Job, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *SignedUrlPayload) SetJobs(v []Job) {
	o.Jobs = v
}

func (o SignedUrlPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignedUrlPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	return toSerialize, nil
}

func (o *SignedUrlPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignedUrlPayload := _SignedUrlPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignedUrlPayload)

	if err != nil {
		return err
	}

	*o = SignedUrlPayload(varSignedUrlPayload)

	return err
}

type NullableSignedUrlPayload struct {
	value *SignedUrlPayload
	isSet bool
}

func (v NullableSignedUrlPayload) Get() *SignedUrlPayload {
	return v.value
}

func (v *NullableSignedUrlPayload) Set(val *SignedUrlPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSignedUrlPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSignedUrlPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignedUrlPayload(val *SignedUrlPayload) *NullableSignedUrlPayload {
	return &NullableSignedUrlPayload{value: val, isSet: true}
}

func (v NullableSignedUrlPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignedUrlPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


