/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestSyncResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestSyncResponse{}

// IngestSyncResponse struct for IngestSyncResponse
type IngestSyncResponse struct {
	SourceAdapter string `json:"source_adapter"`
	SyncedCount int32 `json:"synced_count"`
	Accepted int32 `json:"accepted"`
	Quarantined int32 `json:"quarantined"`
	Rejected int32 `json:"rejected"`
	AcceptedDocIds []string `json:"accepted_doc_ids"`
	QuarantinedDocIds []string `json:"quarantined_doc_ids"`
	RejectedDocIds []string `json:"rejected_doc_ids"`
}

type _IngestSyncResponse IngestSyncResponse

// NewIngestSyncResponse instantiates a new IngestSyncResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestSyncResponse(sourceAdapter string, syncedCount int32, accepted int32, quarantined int32, rejected int32, acceptedDocIds []string, quarantinedDocIds []string, rejectedDocIds []string) *IngestSyncResponse {
	this := IngestSyncResponse{}
	this.SourceAdapter = sourceAdapter
	this.SyncedCount = syncedCount
	this.Accepted = accepted
	this.Quarantined = quarantined
	this.Rejected = rejected
	this.AcceptedDocIds = acceptedDocIds
	this.QuarantinedDocIds = quarantinedDocIds
	this.RejectedDocIds = rejectedDocIds
	return &this
}

// NewIngestSyncResponseWithDefaults instantiates a new IngestSyncResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestSyncResponseWithDefaults() *IngestSyncResponse {
	this := IngestSyncResponse{}
	return &this
}

// GetSourceAdapter returns the SourceAdapter field value
func (o *IngestSyncResponse) GetSourceAdapter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAdapter
}

// GetSourceAdapterOk returns a tuple with the SourceAdapter field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetSourceAdapterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAdapter, true
}

// SetSourceAdapter sets field value
func (o *IngestSyncResponse) SetSourceAdapter(v string) {
	o.SourceAdapter = v
}

// GetSyncedCount returns the SyncedCount field value
func (o *IngestSyncResponse) GetSyncedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SyncedCount
}

// GetSyncedCountOk returns a tuple with the SyncedCount field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetSyncedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyncedCount, true
}

// SetSyncedCount sets field value
func (o *IngestSyncResponse) SetSyncedCount(v int32) {
	o.SyncedCount = v
}

// GetAccepted returns the Accepted field value
func (o *IngestSyncResponse) GetAccepted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetAcceptedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accepted, true
}

// SetAccepted sets field value
func (o *IngestSyncResponse) SetAccepted(v int32) {
	o.Accepted = v
}

// GetQuarantined returns the Quarantined field value
func (o *IngestSyncResponse) GetQuarantined() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quarantined
}

// GetQuarantinedOk returns a tuple with the Quarantined field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetQuarantinedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quarantined, true
}

// SetQuarantined sets field value
func (o *IngestSyncResponse) SetQuarantined(v int32) {
	o.Quarantined = v
}

// GetRejected returns the Rejected field value
func (o *IngestSyncResponse) GetRejected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rejected
}

// GetRejectedOk returns a tuple with the Rejected field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetRejectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rejected, true
}

// SetRejected sets field value
func (o *IngestSyncResponse) SetRejected(v int32) {
	o.Rejected = v
}

// GetAcceptedDocIds returns the AcceptedDocIds field value
func (o *IngestSyncResponse) GetAcceptedDocIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AcceptedDocIds
}

// GetAcceptedDocIdsOk returns a tuple with the AcceptedDocIds field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetAcceptedDocIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AcceptedDocIds, true
}

// SetAcceptedDocIds sets field value
func (o *IngestSyncResponse) SetAcceptedDocIds(v []string) {
	o.AcceptedDocIds = v
}

// GetQuarantinedDocIds returns the QuarantinedDocIds field value
func (o *IngestSyncResponse) GetQuarantinedDocIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.QuarantinedDocIds
}

// GetQuarantinedDocIdsOk returns a tuple with the QuarantinedDocIds field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetQuarantinedDocIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuarantinedDocIds, true
}

// SetQuarantinedDocIds sets field value
func (o *IngestSyncResponse) SetQuarantinedDocIds(v []string) {
	o.QuarantinedDocIds = v
}

// GetRejectedDocIds returns the RejectedDocIds field value
func (o *IngestSyncResponse) GetRejectedDocIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RejectedDocIds
}

// GetRejectedDocIdsOk returns a tuple with the RejectedDocIds field value
// and a boolean to check if the value has been set.
func (o *IngestSyncResponse) GetRejectedDocIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RejectedDocIds, true
}

// SetRejectedDocIds sets field value
func (o *IngestSyncResponse) SetRejectedDocIds(v []string) {
	o.RejectedDocIds = v
}

func (o IngestSyncResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestSyncResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_adapter"] = o.SourceAdapter
	toSerialize["synced_count"] = o.SyncedCount
	toSerialize["accepted"] = o.Accepted
	toSerialize["quarantined"] = o.Quarantined
	toSerialize["rejected"] = o.Rejected
	toSerialize["accepted_doc_ids"] = o.AcceptedDocIds
	toSerialize["quarantined_doc_ids"] = o.QuarantinedDocIds
	toSerialize["rejected_doc_ids"] = o.RejectedDocIds
	return toSerialize, nil
}

func (o *IngestSyncResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_adapter",
		"synced_count",
		"accepted",
		"quarantined",
		"rejected",
		"accepted_doc_ids",
		"quarantined_doc_ids",
		"rejected_doc_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestSyncResponse := _IngestSyncResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIngestSyncResponse)

	if err != nil {
		return err
	}

	*o = IngestSyncResponse(varIngestSyncResponse)

	return err
}

type NullableIngestSyncResponse struct {
	value *IngestSyncResponse
	isSet bool
}

func (v NullableIngestSyncResponse) Get() *IngestSyncResponse {
	return v.value
}

func (v *NullableIngestSyncResponse) Set(val *IngestSyncResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestSyncResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestSyncResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestSyncResponse(val *IngestSyncResponse) *NullableIngestSyncResponse {
	return &NullableIngestSyncResponse{value: val, isSet: true}
}

func (v NullableIngestSyncResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestSyncResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


