/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
)

// checks if the QuarantineReviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuarantineReviewRequest{}

// QuarantineReviewRequest struct for QuarantineReviewRequest
type QuarantineReviewRequest struct {
	// Reviewer reason for approve/reject action
	Reason NullableString `json:"reason,omitempty"`
	RetrieverBackend NullableString `json:"retriever_backend,omitempty"`
	IncidentId NullableString `json:"incident_id,omitempty"`
	Bucket NullableString `json:"bucket,omitempty"`
	DataSourceId NullableString `json:"data_source_id,omitempty"`
}

// NewQuarantineReviewRequest instantiates a new QuarantineReviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuarantineReviewRequest() *QuarantineReviewRequest {
	this := QuarantineReviewRequest{}
	return &this
}

// NewQuarantineReviewRequestWithDefaults instantiates a new QuarantineReviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuarantineReviewRequestWithDefaults() *QuarantineReviewRequest {
	this := QuarantineReviewRequest{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewRequest) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *QuarantineReviewRequest) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *QuarantineReviewRequest) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *QuarantineReviewRequest) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *QuarantineReviewRequest) UnsetReason() {
	o.Reason.Unset()
}

// GetRetrieverBackend returns the RetrieverBackend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewRequest) GetRetrieverBackend() string {
	if o == nil || IsNil(o.RetrieverBackend.Get()) {
		var ret string
		return ret
	}
	return *o.RetrieverBackend.Get()
}

// GetRetrieverBackendOk returns a tuple with the RetrieverBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewRequest) GetRetrieverBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetrieverBackend.Get(), o.RetrieverBackend.IsSet()
}

// HasRetrieverBackend returns a boolean if a field has been set.
func (o *QuarantineReviewRequest) HasRetrieverBackend() bool {
	if o != nil && o.RetrieverBackend.IsSet() {
		return true
	}

	return false
}

// SetRetrieverBackend gets a reference to the given NullableString and assigns it to the RetrieverBackend field.
func (o *QuarantineReviewRequest) SetRetrieverBackend(v string) {
	o.RetrieverBackend.Set(&v)
}
// SetRetrieverBackendNil sets the value for RetrieverBackend to be an explicit nil
func (o *QuarantineReviewRequest) SetRetrieverBackendNil() {
	o.RetrieverBackend.Set(nil)
}

// UnsetRetrieverBackend ensures that no value is present for RetrieverBackend, not even an explicit nil
func (o *QuarantineReviewRequest) UnsetRetrieverBackend() {
	o.RetrieverBackend.Unset()
}

// GetIncidentId returns the IncidentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewRequest) GetIncidentId() string {
	if o == nil || IsNil(o.IncidentId.Get()) {
		var ret string
		return ret
	}
	return *o.IncidentId.Get()
}

// GetIncidentIdOk returns a tuple with the IncidentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewRequest) GetIncidentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncidentId.Get(), o.IncidentId.IsSet()
}

// HasIncidentId returns a boolean if a field has been set.
func (o *QuarantineReviewRequest) HasIncidentId() bool {
	if o != nil && o.IncidentId.IsSet() {
		return true
	}

	return false
}

// SetIncidentId gets a reference to the given NullableString and assigns it to the IncidentId field.
func (o *QuarantineReviewRequest) SetIncidentId(v string) {
	o.IncidentId.Set(&v)
}
// SetIncidentIdNil sets the value for IncidentId to be an explicit nil
func (o *QuarantineReviewRequest) SetIncidentIdNil() {
	o.IncidentId.Set(nil)
}

// UnsetIncidentId ensures that no value is present for IncidentId, not even an explicit nil
func (o *QuarantineReviewRequest) UnsetIncidentId() {
	o.IncidentId.Unset()
}

// GetBucket returns the Bucket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket.Get()) {
		var ret string
		return ret
	}
	return *o.Bucket.Get()
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewRequest) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bucket.Get(), o.Bucket.IsSet()
}

// HasBucket returns a boolean if a field has been set.
func (o *QuarantineReviewRequest) HasBucket() bool {
	if o != nil && o.Bucket.IsSet() {
		return true
	}

	return false
}

// SetBucket gets a reference to the given NullableString and assigns it to the Bucket field.
func (o *QuarantineReviewRequest) SetBucket(v string) {
	o.Bucket.Set(&v)
}
// SetBucketNil sets the value for Bucket to be an explicit nil
func (o *QuarantineReviewRequest) SetBucketNil() {
	o.Bucket.Set(nil)
}

// UnsetBucket ensures that no value is present for Bucket, not even an explicit nil
func (o *QuarantineReviewRequest) UnsetBucket() {
	o.Bucket.Unset()
}

// GetDataSourceId returns the DataSourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewRequest) GetDataSourceId() string {
	if o == nil || IsNil(o.DataSourceId.Get()) {
		var ret string
		return ret
	}
	return *o.DataSourceId.Get()
}

// GetDataSourceIdOk returns a tuple with the DataSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewRequest) GetDataSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataSourceId.Get(), o.DataSourceId.IsSet()
}

// HasDataSourceId returns a boolean if a field has been set.
func (o *QuarantineReviewRequest) HasDataSourceId() bool {
	if o != nil && o.DataSourceId.IsSet() {
		return true
	}

	return false
}

// SetDataSourceId gets a reference to the given NullableString and assigns it to the DataSourceId field.
func (o *QuarantineReviewRequest) SetDataSourceId(v string) {
	o.DataSourceId.Set(&v)
}
// SetDataSourceIdNil sets the value for DataSourceId to be an explicit nil
func (o *QuarantineReviewRequest) SetDataSourceIdNil() {
	o.DataSourceId.Set(nil)
}

// UnsetDataSourceId ensures that no value is present for DataSourceId, not even an explicit nil
func (o *QuarantineReviewRequest) UnsetDataSourceId() {
	o.DataSourceId.Unset()
}

func (o QuarantineReviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuarantineReviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.RetrieverBackend.IsSet() {
		toSerialize["retriever_backend"] = o.RetrieverBackend.Get()
	}
	if o.IncidentId.IsSet() {
		toSerialize["incident_id"] = o.IncidentId.Get()
	}
	if o.Bucket.IsSet() {
		toSerialize["bucket"] = o.Bucket.Get()
	}
	if o.DataSourceId.IsSet() {
		toSerialize["data_source_id"] = o.DataSourceId.Get()
	}
	return toSerialize, nil
}

type NullableQuarantineReviewRequest struct {
	value *QuarantineReviewRequest
	isSet bool
}

func (v NullableQuarantineReviewRequest) Get() *QuarantineReviewRequest {
	return v.value
}

func (v *NullableQuarantineReviewRequest) Set(val *QuarantineReviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuarantineReviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuarantineReviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuarantineReviewRequest(val *QuarantineReviewRequest) *NullableQuarantineReviewRequest {
	return &NullableQuarantineReviewRequest{value: val, isSet: true}
}

func (v NullableQuarantineReviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuarantineReviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


