/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RagQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RagQueryResponse{}

// RagQueryResponse Response body for RAG query.
type RagQueryResponse struct {
	RequestId string `json:"request_id"`
	TenantId NullableString `json:"tenant_id"`
	AppId string `json:"app_id"`
	Query string `json:"query"`
	Answer string `json:"answer"`
	ContextDocs []string `json:"context_docs"`
	Defense DefenseSummary `json:"defense"`
	PolicyEnforcement PolicyEnforcementSummary `json:"policy_enforcement"`
}

type _RagQueryResponse RagQueryResponse

// NewRagQueryResponse instantiates a new RagQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRagQueryResponse(requestId string, tenantId NullableString, appId string, query string, answer string, contextDocs []string, defense DefenseSummary, policyEnforcement PolicyEnforcementSummary) *RagQueryResponse {
	this := RagQueryResponse{}
	this.RequestId = requestId
	this.TenantId = tenantId
	this.AppId = appId
	this.Query = query
	this.Answer = answer
	this.ContextDocs = contextDocs
	this.Defense = defense
	this.PolicyEnforcement = policyEnforcement
	return &this
}

// NewRagQueryResponseWithDefaults instantiates a new RagQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRagQueryResponseWithDefaults() *RagQueryResponse {
	this := RagQueryResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *RagQueryResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *RagQueryResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetTenantId returns the TenantId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RagQueryResponse) GetTenantId() string {
	if o == nil || o.TenantId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RagQueryResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// SetTenantId sets field value
func (o *RagQueryResponse) SetTenantId(v string) {
	o.TenantId.Set(&v)
}

// GetAppId returns the AppId field value
func (o *RagQueryResponse) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *RagQueryResponse) SetAppId(v string) {
	o.AppId = v
}

// GetQuery returns the Query field value
func (o *RagQueryResponse) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *RagQueryResponse) SetQuery(v string) {
	o.Query = v
}

// GetAnswer returns the Answer field value
func (o *RagQueryResponse) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *RagQueryResponse) SetAnswer(v string) {
	o.Answer = v
}

// GetContextDocs returns the ContextDocs field value
func (o *RagQueryResponse) GetContextDocs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ContextDocs
}

// GetContextDocsOk returns a tuple with the ContextDocs field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetContextDocsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContextDocs, true
}

// SetContextDocs sets field value
func (o *RagQueryResponse) SetContextDocs(v []string) {
	o.ContextDocs = v
}

// GetDefense returns the Defense field value
func (o *RagQueryResponse) GetDefense() DefenseSummary {
	if o == nil {
		var ret DefenseSummary
		return ret
	}

	return o.Defense
}

// GetDefenseOk returns a tuple with the Defense field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetDefenseOk() (*DefenseSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Defense, true
}

// SetDefense sets field value
func (o *RagQueryResponse) SetDefense(v DefenseSummary) {
	o.Defense = v
}

// GetPolicyEnforcement returns the PolicyEnforcement field value
func (o *RagQueryResponse) GetPolicyEnforcement() PolicyEnforcementSummary {
	if o == nil {
		var ret PolicyEnforcementSummary
		return ret
	}

	return o.PolicyEnforcement
}

// GetPolicyEnforcementOk returns a tuple with the PolicyEnforcement field value
// and a boolean to check if the value has been set.
func (o *RagQueryResponse) GetPolicyEnforcementOk() (*PolicyEnforcementSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyEnforcement, true
}

// SetPolicyEnforcement sets field value
func (o *RagQueryResponse) SetPolicyEnforcement(v PolicyEnforcementSummary) {
	o.PolicyEnforcement = v
}

func (o RagQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RagQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["request_id"] = o.RequestId
	toSerialize["tenant_id"] = o.TenantId.Get()
	toSerialize["app_id"] = o.AppId
	toSerialize["query"] = o.Query
	toSerialize["answer"] = o.Answer
	toSerialize["context_docs"] = o.ContextDocs
	toSerialize["defense"] = o.Defense
	toSerialize["policy_enforcement"] = o.PolicyEnforcement
	return toSerialize, nil
}

func (o *RagQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"request_id",
		"tenant_id",
		"app_id",
		"query",
		"answer",
		"context_docs",
		"defense",
		"policy_enforcement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRagQueryResponse := _RagQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRagQueryResponse)

	if err != nil {
		return err
	}

	*o = RagQueryResponse(varRagQueryResponse)

	return err
}

type NullableRagQueryResponse struct {
	value *RagQueryResponse
	isSet bool
}

func (v NullableRagQueryResponse) Get() *RagQueryResponse {
	return v.value
}

func (v *NullableRagQueryResponse) Set(val *RagQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRagQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRagQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRagQueryResponse(val *RagQueryResponse) *NullableRagQueryResponse {
	return &NullableRagQueryResponse{value: val, isSet: true}
}

func (v NullableRagQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRagQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


