/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefendResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefendResponseModel{}

// DefendResponseModel Response model for /v1/defend endpoint.
type DefendResponseModel struct {
	Success bool `json:"success"`
	CleanDocuments []string `json:"clean_documents"`
	KeptIndices []int32 `json:"kept_indices"`
	RemovedIndices []int32 `json:"removed_indices"`
	DocumentScores []DocumentScoreModel `json:"document_scores"`
	Stats map[string]interface{} `json:"stats"`
	RequestId NullableString `json:"request_id,omitempty"`
	ProcessingTimeMs float32 `json:"processing_time_ms"`
	Error NullableString `json:"error,omitempty"`
}

type _DefendResponseModel DefendResponseModel

// NewDefendResponseModel instantiates a new DefendResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefendResponseModel(success bool, cleanDocuments []string, keptIndices []int32, removedIndices []int32, documentScores []DocumentScoreModel, stats map[string]interface{}, processingTimeMs float32) *DefendResponseModel {
	this := DefendResponseModel{}
	this.Success = success
	this.CleanDocuments = cleanDocuments
	this.KeptIndices = keptIndices
	this.RemovedIndices = removedIndices
	this.DocumentScores = documentScores
	this.Stats = stats
	this.ProcessingTimeMs = processingTimeMs
	return &this
}

// NewDefendResponseModelWithDefaults instantiates a new DefendResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefendResponseModelWithDefaults() *DefendResponseModel {
	this := DefendResponseModel{}
	return &this
}

// GetSuccess returns the Success field value
func (o *DefendResponseModel) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *DefendResponseModel) SetSuccess(v bool) {
	o.Success = v
}

// GetCleanDocuments returns the CleanDocuments field value
func (o *DefendResponseModel) GetCleanDocuments() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CleanDocuments
}

// GetCleanDocumentsOk returns a tuple with the CleanDocuments field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetCleanDocumentsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CleanDocuments, true
}

// SetCleanDocuments sets field value
func (o *DefendResponseModel) SetCleanDocuments(v []string) {
	o.CleanDocuments = v
}

// GetKeptIndices returns the KeptIndices field value
func (o *DefendResponseModel) GetKeptIndices() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.KeptIndices
}

// GetKeptIndicesOk returns a tuple with the KeptIndices field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetKeptIndicesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeptIndices, true
}

// SetKeptIndices sets field value
func (o *DefendResponseModel) SetKeptIndices(v []int32) {
	o.KeptIndices = v
}

// GetRemovedIndices returns the RemovedIndices field value
func (o *DefendResponseModel) GetRemovedIndices() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.RemovedIndices
}

// GetRemovedIndicesOk returns a tuple with the RemovedIndices field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetRemovedIndicesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemovedIndices, true
}

// SetRemovedIndices sets field value
func (o *DefendResponseModel) SetRemovedIndices(v []int32) {
	o.RemovedIndices = v
}

// GetDocumentScores returns the DocumentScores field value
func (o *DefendResponseModel) GetDocumentScores() []DocumentScoreModel {
	if o == nil {
		var ret []DocumentScoreModel
		return ret
	}

	return o.DocumentScores
}

// GetDocumentScoresOk returns a tuple with the DocumentScores field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetDocumentScoresOk() ([]DocumentScoreModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentScores, true
}

// SetDocumentScores sets field value
func (o *DefendResponseModel) SetDocumentScores(v []DocumentScoreModel) {
	o.DocumentScores = v
}

// GetStats returns the Stats field value
func (o *DefendResponseModel) GetStats() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Stats
}

// GetStatsOk returns a tuple with the Stats field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetStatsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Stats, true
}

// SetStats sets field value
func (o *DefendResponseModel) SetStats(v map[string]interface{}) {
	o.Stats = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefendResponseModel) GetRequestId() string {
	if o == nil || IsNil(o.RequestId.Get()) {
		var ret string
		return ret
	}
	return *o.RequestId.Get()
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefendResponseModel) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestId.Get(), o.RequestId.IsSet()
}

// HasRequestId returns a boolean if a field has been set.
func (o *DefendResponseModel) HasRequestId() bool {
	if o != nil && o.RequestId.IsSet() {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given NullableString and assigns it to the RequestId field.
func (o *DefendResponseModel) SetRequestId(v string) {
	o.RequestId.Set(&v)
}
// SetRequestIdNil sets the value for RequestId to be an explicit nil
func (o *DefendResponseModel) SetRequestIdNil() {
	o.RequestId.Set(nil)
}

// UnsetRequestId ensures that no value is present for RequestId, not even an explicit nil
func (o *DefendResponseModel) UnsetRequestId() {
	o.RequestId.Unset()
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value
func (o *DefendResponseModel) GetProcessingTimeMs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value
// and a boolean to check if the value has been set.
func (o *DefendResponseModel) GetProcessingTimeMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingTimeMs, true
}

// SetProcessingTimeMs sets field value
func (o *DefendResponseModel) SetProcessingTimeMs(v float32) {
	o.ProcessingTimeMs = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefendResponseModel) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefendResponseModel) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *DefendResponseModel) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *DefendResponseModel) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *DefendResponseModel) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *DefendResponseModel) UnsetError() {
	o.Error.Unset()
}

func (o DefendResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefendResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["clean_documents"] = o.CleanDocuments
	toSerialize["kept_indices"] = o.KeptIndices
	toSerialize["removed_indices"] = o.RemovedIndices
	toSerialize["document_scores"] = o.DocumentScores
	toSerialize["stats"] = o.Stats
	if o.RequestId.IsSet() {
		toSerialize["request_id"] = o.RequestId.Get()
	}
	toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	return toSerialize, nil
}

func (o *DefendResponseModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"clean_documents",
		"kept_indices",
		"removed_indices",
		"document_scores",
		"stats",
		"processing_time_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefendResponseModel := _DefendResponseModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefendResponseModel)

	if err != nil {
		return err
	}

	*o = DefendResponseModel(varDefendResponseModel)

	return err
}

type NullableDefendResponseModel struct {
	value *DefendResponseModel
	isSet bool
}

func (v NullableDefendResponseModel) Get() *DefendResponseModel {
	return v.value
}

func (v *NullableDefendResponseModel) Set(val *DefendResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDefendResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDefendResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefendResponseModel(val *DefendResponseModel) *NullableDefendResponseModel {
	return &NullableDefendResponseModel{value: val, isSet: true}
}

func (v NullableDefendResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefendResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


