/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestDocument{}

// IngestDocument struct for IngestDocument
type IngestDocument struct {
	// Optional document identifier
	DocId NullableString `json:"doc_id,omitempty"`
	// Document text/content
	Text string `json:"text"`
	// Document metadata, including source_type
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _IngestDocument IngestDocument

// NewIngestDocument instantiates a new IngestDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestDocument(text string) *IngestDocument {
	this := IngestDocument{}
	this.Text = text
	return &this
}

// NewIngestDocumentWithDefaults instantiates a new IngestDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestDocumentWithDefaults() *IngestDocument {
	this := IngestDocument{}
	return &this
}

// GetDocId returns the DocId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestDocument) GetDocId() string {
	if o == nil || IsNil(o.DocId.Get()) {
		var ret string
		return ret
	}
	return *o.DocId.Get()
}

// GetDocIdOk returns a tuple with the DocId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestDocument) GetDocIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocId.Get(), o.DocId.IsSet()
}

// HasDocId returns a boolean if a field has been set.
func (o *IngestDocument) HasDocId() bool {
	if o != nil && o.DocId.IsSet() {
		return true
	}

	return false
}

// SetDocId gets a reference to the given NullableString and assigns it to the DocId field.
func (o *IngestDocument) SetDocId(v string) {
	o.DocId.Set(&v)
}
// SetDocIdNil sets the value for DocId to be an explicit nil
func (o *IngestDocument) SetDocIdNil() {
	o.DocId.Set(nil)
}

// UnsetDocId ensures that no value is present for DocId, not even an explicit nil
func (o *IngestDocument) UnsetDocId() {
	o.DocId.Unset()
}

// GetText returns the Text field value
func (o *IngestDocument) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *IngestDocument) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *IngestDocument) SetText(v string) {
	o.Text = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *IngestDocument) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestDocument) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *IngestDocument) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *IngestDocument) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o IngestDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DocId.IsSet() {
		toSerialize["doc_id"] = o.DocId.Get()
	}
	toSerialize["text"] = o.Text
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *IngestDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestDocument := _IngestDocument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIngestDocument)

	if err != nil {
		return err
	}

	*o = IngestDocument(varIngestDocument)

	return err
}

type NullableIngestDocument struct {
	value *IngestDocument
	isSet bool
}

func (v NullableIngestDocument) Get() *IngestDocument {
	return v.value
}

func (v *NullableIngestDocument) Set(val *IngestDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestDocument(val *IngestDocument) *NullableIngestDocument {
	return &NullableIngestDocument{value: val, isSet: true}
}

func (v NullableIngestDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


