/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QuarantineReviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuarantineReviewResponse{}

// QuarantineReviewResponse struct for QuarantineReviewResponse
type QuarantineReviewResponse struct {
	DocId string `json:"doc_id"`
	PreviousStatus string `json:"previous_status"`
	NewStatus string `json:"new_status"`
	Indexed *bool `json:"indexed,omitempty"`
	IndexError NullableString `json:"index_error,omitempty"`
	Review map[string]interface{} `json:"review,omitempty"`
}

type _QuarantineReviewResponse QuarantineReviewResponse

// NewQuarantineReviewResponse instantiates a new QuarantineReviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuarantineReviewResponse(docId string, previousStatus string, newStatus string) *QuarantineReviewResponse {
	this := QuarantineReviewResponse{}
	this.DocId = docId
	this.PreviousStatus = previousStatus
	this.NewStatus = newStatus
	var indexed bool = false
	this.Indexed = &indexed
	return &this
}

// NewQuarantineReviewResponseWithDefaults instantiates a new QuarantineReviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuarantineReviewResponseWithDefaults() *QuarantineReviewResponse {
	this := QuarantineReviewResponse{}
	var indexed bool = false
	this.Indexed = &indexed
	return &this
}

// GetDocId returns the DocId field value
func (o *QuarantineReviewResponse) GetDocId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocId
}

// GetDocIdOk returns a tuple with the DocId field value
// and a boolean to check if the value has been set.
func (o *QuarantineReviewResponse) GetDocIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocId, true
}

// SetDocId sets field value
func (o *QuarantineReviewResponse) SetDocId(v string) {
	o.DocId = v
}

// GetPreviousStatus returns the PreviousStatus field value
func (o *QuarantineReviewResponse) GetPreviousStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviousStatus
}

// GetPreviousStatusOk returns a tuple with the PreviousStatus field value
// and a boolean to check if the value has been set.
func (o *QuarantineReviewResponse) GetPreviousStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousStatus, true
}

// SetPreviousStatus sets field value
func (o *QuarantineReviewResponse) SetPreviousStatus(v string) {
	o.PreviousStatus = v
}

// GetNewStatus returns the NewStatus field value
func (o *QuarantineReviewResponse) GetNewStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewStatus
}

// GetNewStatusOk returns a tuple with the NewStatus field value
// and a boolean to check if the value has been set.
func (o *QuarantineReviewResponse) GetNewStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewStatus, true
}

// SetNewStatus sets field value
func (o *QuarantineReviewResponse) SetNewStatus(v string) {
	o.NewStatus = v
}

// GetIndexed returns the Indexed field value if set, zero value otherwise.
func (o *QuarantineReviewResponse) GetIndexed() bool {
	if o == nil || IsNil(o.Indexed) {
		var ret bool
		return ret
	}
	return *o.Indexed
}

// GetIndexedOk returns a tuple with the Indexed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineReviewResponse) GetIndexedOk() (*bool, bool) {
	if o == nil || IsNil(o.Indexed) {
		return nil, false
	}
	return o.Indexed, true
}

// HasIndexed returns a boolean if a field has been set.
func (o *QuarantineReviewResponse) HasIndexed() bool {
	if o != nil && !IsNil(o.Indexed) {
		return true
	}

	return false
}

// SetIndexed gets a reference to the given bool and assigns it to the Indexed field.
func (o *QuarantineReviewResponse) SetIndexed(v bool) {
	o.Indexed = &v
}

// GetIndexError returns the IndexError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuarantineReviewResponse) GetIndexError() string {
	if o == nil || IsNil(o.IndexError.Get()) {
		var ret string
		return ret
	}
	return *o.IndexError.Get()
}

// GetIndexErrorOk returns a tuple with the IndexError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuarantineReviewResponse) GetIndexErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IndexError.Get(), o.IndexError.IsSet()
}

// HasIndexError returns a boolean if a field has been set.
func (o *QuarantineReviewResponse) HasIndexError() bool {
	if o != nil && o.IndexError.IsSet() {
		return true
	}

	return false
}

// SetIndexError gets a reference to the given NullableString and assigns it to the IndexError field.
func (o *QuarantineReviewResponse) SetIndexError(v string) {
	o.IndexError.Set(&v)
}
// SetIndexErrorNil sets the value for IndexError to be an explicit nil
func (o *QuarantineReviewResponse) SetIndexErrorNil() {
	o.IndexError.Set(nil)
}

// UnsetIndexError ensures that no value is present for IndexError, not even an explicit nil
func (o *QuarantineReviewResponse) UnsetIndexError() {
	o.IndexError.Unset()
}

// GetReview returns the Review field value if set, zero value otherwise.
func (o *QuarantineReviewResponse) GetReview() map[string]interface{} {
	if o == nil || IsNil(o.Review) {
		var ret map[string]interface{}
		return ret
	}
	return o.Review
}

// GetReviewOk returns a tuple with the Review field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuarantineReviewResponse) GetReviewOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Review) {
		return map[string]interface{}{}, false
	}
	return o.Review, true
}

// HasReview returns a boolean if a field has been set.
func (o *QuarantineReviewResponse) HasReview() bool {
	if o != nil && !IsNil(o.Review) {
		return true
	}

	return false
}

// SetReview gets a reference to the given map[string]interface{} and assigns it to the Review field.
func (o *QuarantineReviewResponse) SetReview(v map[string]interface{}) {
	o.Review = v
}

func (o QuarantineReviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuarantineReviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["doc_id"] = o.DocId
	toSerialize["previous_status"] = o.PreviousStatus
	toSerialize["new_status"] = o.NewStatus
	if !IsNil(o.Indexed) {
		toSerialize["indexed"] = o.Indexed
	}
	if o.IndexError.IsSet() {
		toSerialize["index_error"] = o.IndexError.Get()
	}
	if !IsNil(o.Review) {
		toSerialize["review"] = o.Review
	}
	return toSerialize, nil
}

func (o *QuarantineReviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"doc_id",
		"previous_status",
		"new_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuarantineReviewResponse := _QuarantineReviewResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuarantineReviewResponse)

	if err != nil {
		return err
	}

	*o = QuarantineReviewResponse(varQuarantineReviewResponse)

	return err
}

type NullableQuarantineReviewResponse struct {
	value *QuarantineReviewResponse
	isSet bool
}

func (v NullableQuarantineReviewResponse) Get() *QuarantineReviewResponse {
	return v.value
}

func (v *NullableQuarantineReviewResponse) Set(val *QuarantineReviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQuarantineReviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQuarantineReviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuarantineReviewResponse(val *QuarantineReviewResponse) *NullableQuarantineReviewResponse {
	return &NullableQuarantineReviewResponse{value: val, isSet: true}
}

func (v NullableQuarantineReviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuarantineReviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


