/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefendRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefendRequestModel{}

// DefendRequestModel Request model for /v1/defend endpoint.
type DefendRequestModel struct {
	// The query string
	Query string `json:"query"`
	// List of retrieved documents
	Documents []string `json:"documents"`
	// Defense mode
	Mode *string `json:"mode,omitempty"`
	// Number of documents to return
	TopK NullableInt32 `json:"top_k,omitempty"`
	// Tenant identifier
	TenantId NullableString `json:"tenant_id,omitempty"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _DefendRequestModel DefendRequestModel

// NewDefendRequestModel instantiates a new DefendRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefendRequestModel(query string, documents []string) *DefendRequestModel {
	this := DefendRequestModel{}
	this.Query = query
	this.Documents = documents
	var mode string = "multihop"
	this.Mode = &mode
	return &this
}

// NewDefendRequestModelWithDefaults instantiates a new DefendRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefendRequestModelWithDefaults() *DefendRequestModel {
	this := DefendRequestModel{}
	var mode string = "multihop"
	this.Mode = &mode
	return &this
}

// GetQuery returns the Query field value
func (o *DefendRequestModel) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *DefendRequestModel) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *DefendRequestModel) SetQuery(v string) {
	o.Query = v
}

// GetDocuments returns the Documents field value
func (o *DefendRequestModel) GetDocuments() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *DefendRequestModel) GetDocumentsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *DefendRequestModel) SetDocuments(v []string) {
	o.Documents = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *DefendRequestModel) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefendRequestModel) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *DefendRequestModel) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *DefendRequestModel) SetMode(v string) {
	o.Mode = &v
}

// GetTopK returns the TopK field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefendRequestModel) GetTopK() int32 {
	if o == nil || IsNil(o.TopK.Get()) {
		var ret int32
		return ret
	}
	return *o.TopK.Get()
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefendRequestModel) GetTopKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopK.Get(), o.TopK.IsSet()
}

// HasTopK returns a boolean if a field has been set.
func (o *DefendRequestModel) HasTopK() bool {
	if o != nil && o.TopK.IsSet() {
		return true
	}

	return false
}

// SetTopK gets a reference to the given NullableInt32 and assigns it to the TopK field.
func (o *DefendRequestModel) SetTopK(v int32) {
	o.TopK.Set(&v)
}
// SetTopKNil sets the value for TopK to be an explicit nil
func (o *DefendRequestModel) SetTopKNil() {
	o.TopK.Set(nil)
}

// UnsetTopK ensures that no value is present for TopK, not even an explicit nil
func (o *DefendRequestModel) UnsetTopK() {
	o.TopK.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefendRequestModel) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefendRequestModel) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *DefendRequestModel) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *DefendRequestModel) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *DefendRequestModel) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *DefendRequestModel) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DefendRequestModel) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefendRequestModel) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DefendRequestModel) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *DefendRequestModel) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o DefendRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefendRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	toSerialize["documents"] = o.Documents
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if o.TopK.IsSet() {
		toSerialize["top_k"] = o.TopK.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *DefendRequestModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
		"documents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefendRequestModel := _DefendRequestModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefendRequestModel)

	if err != nil {
		return err
	}

	*o = DefendRequestModel(varDefendRequestModel)

	return err
}

type NullableDefendRequestModel struct {
	value *DefendRequestModel
	isSet bool
}

func (v NullableDefendRequestModel) Get() *DefendRequestModel {
	return v.value
}

func (v *NullableDefendRequestModel) Set(val *DefendRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDefendRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDefendRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefendRequestModel(val *DefendRequestModel) *NullableDefendRequestModel {
	return &NullableDefendRequestModel{value: val, isSet: true}
}

func (v NullableDefendRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefendRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


