/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestCommitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestCommitRequest{}

// IngestCommitRequest struct for IngestCommitRequest
type IngestCommitRequest struct {
	TenantId NullableString `json:"tenant_id,omitempty"`
	AppId NullableString `json:"app_id,omitempty"`
	StoreQuarantine *bool `json:"store_quarantine,omitempty"`
	RetrieverBackend NullableString `json:"retriever_backend,omitempty"`
	SourceAdapter NullableString `json:"source_adapter,omitempty"`
	Index NullableString `json:"index,omitempty"`
	Documents []IngestDocument `json:"documents"`
	Bucket NullableString `json:"bucket,omitempty"`
	DataSourceId NullableString `json:"data_source_id,omitempty"`
}

type _IngestCommitRequest IngestCommitRequest

// NewIngestCommitRequest instantiates a new IngestCommitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestCommitRequest(documents []IngestDocument) *IngestCommitRequest {
	this := IngestCommitRequest{}
	var storeQuarantine bool = true
	this.StoreQuarantine = &storeQuarantine
	this.Documents = documents
	return &this
}

// NewIngestCommitRequestWithDefaults instantiates a new IngestCommitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestCommitRequestWithDefaults() *IngestCommitRequest {
	this := IngestCommitRequest{}
	var storeQuarantine bool = true
	this.StoreQuarantine = &storeQuarantine
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *IngestCommitRequest) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *IngestCommitRequest) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *IngestCommitRequest) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetAppId() string {
	if o == nil || IsNil(o.AppId.Get()) {
		var ret string
		return ret
	}
	return *o.AppId.Get()
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppId.Get(), o.AppId.IsSet()
}

// HasAppId returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasAppId() bool {
	if o != nil && o.AppId.IsSet() {
		return true
	}

	return false
}

// SetAppId gets a reference to the given NullableString and assigns it to the AppId field.
func (o *IngestCommitRequest) SetAppId(v string) {
	o.AppId.Set(&v)
}
// SetAppIdNil sets the value for AppId to be an explicit nil
func (o *IngestCommitRequest) SetAppIdNil() {
	o.AppId.Set(nil)
}

// UnsetAppId ensures that no value is present for AppId, not even an explicit nil
func (o *IngestCommitRequest) UnsetAppId() {
	o.AppId.Unset()
}

// GetStoreQuarantine returns the StoreQuarantine field value if set, zero value otherwise.
func (o *IngestCommitRequest) GetStoreQuarantine() bool {
	if o == nil || IsNil(o.StoreQuarantine) {
		var ret bool
		return ret
	}
	return *o.StoreQuarantine
}

// GetStoreQuarantineOk returns a tuple with the StoreQuarantine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestCommitRequest) GetStoreQuarantineOk() (*bool, bool) {
	if o == nil || IsNil(o.StoreQuarantine) {
		return nil, false
	}
	return o.StoreQuarantine, true
}

// HasStoreQuarantine returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasStoreQuarantine() bool {
	if o != nil && !IsNil(o.StoreQuarantine) {
		return true
	}

	return false
}

// SetStoreQuarantine gets a reference to the given bool and assigns it to the StoreQuarantine field.
func (o *IngestCommitRequest) SetStoreQuarantine(v bool) {
	o.StoreQuarantine = &v
}

// GetRetrieverBackend returns the RetrieverBackend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetRetrieverBackend() string {
	if o == nil || IsNil(o.RetrieverBackend.Get()) {
		var ret string
		return ret
	}
	return *o.RetrieverBackend.Get()
}

// GetRetrieverBackendOk returns a tuple with the RetrieverBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetRetrieverBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetrieverBackend.Get(), o.RetrieverBackend.IsSet()
}

// HasRetrieverBackend returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasRetrieverBackend() bool {
	if o != nil && o.RetrieverBackend.IsSet() {
		return true
	}

	return false
}

// SetRetrieverBackend gets a reference to the given NullableString and assigns it to the RetrieverBackend field.
func (o *IngestCommitRequest) SetRetrieverBackend(v string) {
	o.RetrieverBackend.Set(&v)
}
// SetRetrieverBackendNil sets the value for RetrieverBackend to be an explicit nil
func (o *IngestCommitRequest) SetRetrieverBackendNil() {
	o.RetrieverBackend.Set(nil)
}

// UnsetRetrieverBackend ensures that no value is present for RetrieverBackend, not even an explicit nil
func (o *IngestCommitRequest) UnsetRetrieverBackend() {
	o.RetrieverBackend.Unset()
}

// GetSourceAdapter returns the SourceAdapter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetSourceAdapter() string {
	if o == nil || IsNil(o.SourceAdapter.Get()) {
		var ret string
		return ret
	}
	return *o.SourceAdapter.Get()
}

// GetSourceAdapterOk returns a tuple with the SourceAdapter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetSourceAdapterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceAdapter.Get(), o.SourceAdapter.IsSet()
}

// HasSourceAdapter returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasSourceAdapter() bool {
	if o != nil && o.SourceAdapter.IsSet() {
		return true
	}

	return false
}

// SetSourceAdapter gets a reference to the given NullableString and assigns it to the SourceAdapter field.
func (o *IngestCommitRequest) SetSourceAdapter(v string) {
	o.SourceAdapter.Set(&v)
}
// SetSourceAdapterNil sets the value for SourceAdapter to be an explicit nil
func (o *IngestCommitRequest) SetSourceAdapterNil() {
	o.SourceAdapter.Set(nil)
}

// UnsetSourceAdapter ensures that no value is present for SourceAdapter, not even an explicit nil
func (o *IngestCommitRequest) UnsetSourceAdapter() {
	o.SourceAdapter.Unset()
}

// GetIndex returns the Index field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetIndex() string {
	if o == nil || IsNil(o.Index.Get()) {
		var ret string
		return ret
	}
	return *o.Index.Get()
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Index.Get(), o.Index.IsSet()
}

// HasIndex returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasIndex() bool {
	if o != nil && o.Index.IsSet() {
		return true
	}

	return false
}

// SetIndex gets a reference to the given NullableString and assigns it to the Index field.
func (o *IngestCommitRequest) SetIndex(v string) {
	o.Index.Set(&v)
}
// SetIndexNil sets the value for Index to be an explicit nil
func (o *IngestCommitRequest) SetIndexNil() {
	o.Index.Set(nil)
}

// UnsetIndex ensures that no value is present for Index, not even an explicit nil
func (o *IngestCommitRequest) UnsetIndex() {
	o.Index.Unset()
}

// GetDocuments returns the Documents field value
func (o *IngestCommitRequest) GetDocuments() []IngestDocument {
	if o == nil {
		var ret []IngestDocument
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *IngestCommitRequest) GetDocumentsOk() ([]IngestDocument, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *IngestCommitRequest) SetDocuments(v []IngestDocument) {
	o.Documents = v
}

// GetBucket returns the Bucket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket.Get()) {
		var ret string
		return ret
	}
	return *o.Bucket.Get()
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bucket.Get(), o.Bucket.IsSet()
}

// HasBucket returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasBucket() bool {
	if o != nil && o.Bucket.IsSet() {
		return true
	}

	return false
}

// SetBucket gets a reference to the given NullableString and assigns it to the Bucket field.
func (o *IngestCommitRequest) SetBucket(v string) {
	o.Bucket.Set(&v)
}
// SetBucketNil sets the value for Bucket to be an explicit nil
func (o *IngestCommitRequest) SetBucketNil() {
	o.Bucket.Set(nil)
}

// UnsetBucket ensures that no value is present for Bucket, not even an explicit nil
func (o *IngestCommitRequest) UnsetBucket() {
	o.Bucket.Unset()
}

// GetDataSourceId returns the DataSourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestCommitRequest) GetDataSourceId() string {
	if o == nil || IsNil(o.DataSourceId.Get()) {
		var ret string
		return ret
	}
	return *o.DataSourceId.Get()
}

// GetDataSourceIdOk returns a tuple with the DataSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestCommitRequest) GetDataSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataSourceId.Get(), o.DataSourceId.IsSet()
}

// HasDataSourceId returns a boolean if a field has been set.
func (o *IngestCommitRequest) HasDataSourceId() bool {
	if o != nil && o.DataSourceId.IsSet() {
		return true
	}

	return false
}

// SetDataSourceId gets a reference to the given NullableString and assigns it to the DataSourceId field.
func (o *IngestCommitRequest) SetDataSourceId(v string) {
	o.DataSourceId.Set(&v)
}
// SetDataSourceIdNil sets the value for DataSourceId to be an explicit nil
func (o *IngestCommitRequest) SetDataSourceIdNil() {
	o.DataSourceId.Set(nil)
}

// UnsetDataSourceId ensures that no value is present for DataSourceId, not even an explicit nil
func (o *IngestCommitRequest) UnsetDataSourceId() {
	o.DataSourceId.Unset()
}

func (o IngestCommitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestCommitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	if o.AppId.IsSet() {
		toSerialize["app_id"] = o.AppId.Get()
	}
	if !IsNil(o.StoreQuarantine) {
		toSerialize["store_quarantine"] = o.StoreQuarantine
	}
	if o.RetrieverBackend.IsSet() {
		toSerialize["retriever_backend"] = o.RetrieverBackend.Get()
	}
	if o.SourceAdapter.IsSet() {
		toSerialize["source_adapter"] = o.SourceAdapter.Get()
	}
	if o.Index.IsSet() {
		toSerialize["index"] = o.Index.Get()
	}
	toSerialize["documents"] = o.Documents
	if o.Bucket.IsSet() {
		toSerialize["bucket"] = o.Bucket.Get()
	}
	if o.DataSourceId.IsSet() {
		toSerialize["data_source_id"] = o.DataSourceId.Get()
	}
	return toSerialize, nil
}

func (o *IngestCommitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestCommitRequest := _IngestCommitRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIngestCommitRequest)

	if err != nil {
		return err
	}

	*o = IngestCommitRequest(varIngestCommitRequest)

	return err
}

type NullableIngestCommitRequest struct {
	value *IngestCommitRequest
	isSet bool
}

func (v NullableIngestCommitRequest) Get() *IngestCommitRequest {
	return v.value
}

func (v *NullableIngestCommitRequest) Set(val *IngestCommitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestCommitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestCommitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestCommitRequest(val *IngestCommitRequest) *NullableIngestCommitRequest {
	return &NullableIngestCommitRequest{value: val, isSet: true}
}

func (v NullableIngestCommitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestCommitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


