/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RagQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RagQueryRequest{}

// RagQueryRequest Request body for RAG query.
type RagQueryRequest struct {
	// User query
	Query string `json:"query"`
	// Number of documents to retrieve (mock retriever)
	TopK *int32 `json:"top_k,omitempty"`
	// Channel identifier (web, api, mobile, etc.)
	Channel NullableString `json:"channel,omitempty"`
	RetrieverBackend NullableString `json:"retriever_backend,omitempty"`
}

type _RagQueryRequest RagQueryRequest

// NewRagQueryRequest instantiates a new RagQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRagQueryRequest(query string) *RagQueryRequest {
	this := RagQueryRequest{}
	this.Query = query
	var topK int32 = 10
	this.TopK = &topK
	return &this
}

// NewRagQueryRequestWithDefaults instantiates a new RagQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRagQueryRequestWithDefaults() *RagQueryRequest {
	this := RagQueryRequest{}
	var topK int32 = 10
	this.TopK = &topK
	return &this
}

// GetQuery returns the Query field value
func (o *RagQueryRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *RagQueryRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *RagQueryRequest) SetQuery(v string) {
	o.Query = v
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (o *RagQueryRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK) {
		var ret int32
		return ret
	}
	return *o.TopK
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RagQueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.TopK) {
		return nil, false
	}
	return o.TopK, true
}

// HasTopK returns a boolean if a field has been set.
func (o *RagQueryRequest) HasTopK() bool {
	if o != nil && !IsNil(o.TopK) {
		return true
	}

	return false
}

// SetTopK gets a reference to the given int32 and assigns it to the TopK field.
func (o *RagQueryRequest) SetTopK(v int32) {
	o.TopK = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RagQueryRequest) GetChannel() string {
	if o == nil || IsNil(o.Channel.Get()) {
		var ret string
		return ret
	}
	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RagQueryRequest) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// HasChannel returns a boolean if a field has been set.
func (o *RagQueryRequest) HasChannel() bool {
	if o != nil && o.Channel.IsSet() {
		return true
	}

	return false
}

// SetChannel gets a reference to the given NullableString and assigns it to the Channel field.
func (o *RagQueryRequest) SetChannel(v string) {
	o.Channel.Set(&v)
}
// SetChannelNil sets the value for Channel to be an explicit nil
func (o *RagQueryRequest) SetChannelNil() {
	o.Channel.Set(nil)
}

// UnsetChannel ensures that no value is present for Channel, not even an explicit nil
func (o *RagQueryRequest) UnsetChannel() {
	o.Channel.Unset()
}

// GetRetrieverBackend returns the RetrieverBackend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RagQueryRequest) GetRetrieverBackend() string {
	if o == nil || IsNil(o.RetrieverBackend.Get()) {
		var ret string
		return ret
	}
	return *o.RetrieverBackend.Get()
}

// GetRetrieverBackendOk returns a tuple with the RetrieverBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RagQueryRequest) GetRetrieverBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetrieverBackend.Get(), o.RetrieverBackend.IsSet()
}

// HasRetrieverBackend returns a boolean if a field has been set.
func (o *RagQueryRequest) HasRetrieverBackend() bool {
	if o != nil && o.RetrieverBackend.IsSet() {
		return true
	}

	return false
}

// SetRetrieverBackend gets a reference to the given NullableString and assigns it to the RetrieverBackend field.
func (o *RagQueryRequest) SetRetrieverBackend(v string) {
	o.RetrieverBackend.Set(&v)
}
// SetRetrieverBackendNil sets the value for RetrieverBackend to be an explicit nil
func (o *RagQueryRequest) SetRetrieverBackendNil() {
	o.RetrieverBackend.Set(nil)
}

// UnsetRetrieverBackend ensures that no value is present for RetrieverBackend, not even an explicit nil
func (o *RagQueryRequest) UnsetRetrieverBackend() {
	o.RetrieverBackend.Unset()
}

func (o RagQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RagQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.TopK) {
		toSerialize["top_k"] = o.TopK
	}
	if o.Channel.IsSet() {
		toSerialize["channel"] = o.Channel.Get()
	}
	if o.RetrieverBackend.IsSet() {
		toSerialize["retriever_backend"] = o.RetrieverBackend.Get()
	}
	return toSerialize, nil
}

func (o *RagQueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRagQueryRequest := _RagQueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRagQueryRequest)

	if err != nil {
		return err
	}

	*o = RagQueryRequest(varRagQueryRequest)

	return err
}

type NullableRagQueryRequest struct {
	value *RagQueryRequest
	isSet bool
}

func (v NullableRagQueryRequest) Get() *RagQueryRequest {
	return v.value
}

func (v *NullableRagQueryRequest) Set(val *RagQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRagQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRagQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRagQueryRequest(val *RagQueryRequest) *NullableRagQueryRequest {
	return &NullableRagQueryRequest{value: val, isSet: true}
}

func (v NullableRagQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRagQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


