/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
)

// checks if the IngestSyncRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestSyncRequest{}

// IngestSyncRequest struct for IngestSyncRequest
type IngestSyncRequest struct {
	TenantId NullableString `json:"tenant_id,omitempty"`
	AppId NullableString `json:"app_id,omitempty"`
	StoreQuarantine *bool `json:"store_quarantine,omitempty"`
	Bucket NullableString `json:"bucket,omitempty"`
	DataSourceId NullableString `json:"data_source_id,omitempty"`
	Files []string `json:"files,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IngestSyncRequest IngestSyncRequest

// NewIngestSyncRequest instantiates a new IngestSyncRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestSyncRequest() *IngestSyncRequest {
	this := IngestSyncRequest{}
	var storeQuarantine bool = true
	this.StoreQuarantine = &storeQuarantine
	return &this
}

// NewIngestSyncRequestWithDefaults instantiates a new IngestSyncRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestSyncRequestWithDefaults() *IngestSyncRequest {
	this := IngestSyncRequest{}
	var storeQuarantine bool = true
	this.StoreQuarantine = &storeQuarantine
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestSyncRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestSyncRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *IngestSyncRequest) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *IngestSyncRequest) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *IngestSyncRequest) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetAppId returns the AppId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestSyncRequest) GetAppId() string {
	if o == nil || IsNil(o.AppId.Get()) {
		var ret string
		return ret
	}
	return *o.AppId.Get()
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestSyncRequest) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppId.Get(), o.AppId.IsSet()
}

// HasAppId returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasAppId() bool {
	if o != nil && o.AppId.IsSet() {
		return true
	}

	return false
}

// SetAppId gets a reference to the given NullableString and assigns it to the AppId field.
func (o *IngestSyncRequest) SetAppId(v string) {
	o.AppId.Set(&v)
}
// SetAppIdNil sets the value for AppId to be an explicit nil
func (o *IngestSyncRequest) SetAppIdNil() {
	o.AppId.Set(nil)
}

// UnsetAppId ensures that no value is present for AppId, not even an explicit nil
func (o *IngestSyncRequest) UnsetAppId() {
	o.AppId.Unset()
}

// GetStoreQuarantine returns the StoreQuarantine field value if set, zero value otherwise.
func (o *IngestSyncRequest) GetStoreQuarantine() bool {
	if o == nil || IsNil(o.StoreQuarantine) {
		var ret bool
		return ret
	}
	return *o.StoreQuarantine
}

// GetStoreQuarantineOk returns a tuple with the StoreQuarantine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestSyncRequest) GetStoreQuarantineOk() (*bool, bool) {
	if o == nil || IsNil(o.StoreQuarantine) {
		return nil, false
	}
	return o.StoreQuarantine, true
}

// HasStoreQuarantine returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasStoreQuarantine() bool {
	if o != nil && !IsNil(o.StoreQuarantine) {
		return true
	}

	return false
}

// SetStoreQuarantine gets a reference to the given bool and assigns it to the StoreQuarantine field.
func (o *IngestSyncRequest) SetStoreQuarantine(v bool) {
	o.StoreQuarantine = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestSyncRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket.Get()) {
		var ret string
		return ret
	}
	return *o.Bucket.Get()
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestSyncRequest) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bucket.Get(), o.Bucket.IsSet()
}

// HasBucket returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasBucket() bool {
	if o != nil && o.Bucket.IsSet() {
		return true
	}

	return false
}

// SetBucket gets a reference to the given NullableString and assigns it to the Bucket field.
func (o *IngestSyncRequest) SetBucket(v string) {
	o.Bucket.Set(&v)
}
// SetBucketNil sets the value for Bucket to be an explicit nil
func (o *IngestSyncRequest) SetBucketNil() {
	o.Bucket.Set(nil)
}

// UnsetBucket ensures that no value is present for Bucket, not even an explicit nil
func (o *IngestSyncRequest) UnsetBucket() {
	o.Bucket.Unset()
}

// GetDataSourceId returns the DataSourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestSyncRequest) GetDataSourceId() string {
	if o == nil || IsNil(o.DataSourceId.Get()) {
		var ret string
		return ret
	}
	return *o.DataSourceId.Get()
}

// GetDataSourceIdOk returns a tuple with the DataSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestSyncRequest) GetDataSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataSourceId.Get(), o.DataSourceId.IsSet()
}

// HasDataSourceId returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasDataSourceId() bool {
	if o != nil && o.DataSourceId.IsSet() {
		return true
	}

	return false
}

// SetDataSourceId gets a reference to the given NullableString and assigns it to the DataSourceId field.
func (o *IngestSyncRequest) SetDataSourceId(v string) {
	o.DataSourceId.Set(&v)
}
// SetDataSourceIdNil sets the value for DataSourceId to be an explicit nil
func (o *IngestSyncRequest) SetDataSourceIdNil() {
	o.DataSourceId.Set(nil)
}

// UnsetDataSourceId ensures that no value is present for DataSourceId, not even an explicit nil
func (o *IngestSyncRequest) UnsetDataSourceId() {
	o.DataSourceId.Unset()
}

// GetFiles returns the Files field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IngestSyncRequest) GetFiles() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IngestSyncRequest) GetFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *IngestSyncRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []string and assigns it to the Files field.
func (o *IngestSyncRequest) SetFiles(v []string) {
	o.Files = v
}

func (o IngestSyncRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestSyncRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	if o.AppId.IsSet() {
		toSerialize["app_id"] = o.AppId.Get()
	}
	if !IsNil(o.StoreQuarantine) {
		toSerialize["store_quarantine"] = o.StoreQuarantine
	}
	if o.Bucket.IsSet() {
		toSerialize["bucket"] = o.Bucket.Get()
	}
	if o.DataSourceId.IsSet() {
		toSerialize["data_source_id"] = o.DataSourceId.Get()
	}
	if o.Files != nil {
		toSerialize["files"] = o.Files
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IngestSyncRequest) UnmarshalJSON(data []byte) (err error) {
	varIngestSyncRequest := _IngestSyncRequest{}

	err = json.Unmarshal(data, &varIngestSyncRequest)

	if err != nil {
		return err
	}

	*o = IngestSyncRequest(varIngestSyncRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "app_id")
		delete(additionalProperties, "store_quarantine")
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "data_source_id")
		delete(additionalProperties, "files")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIngestSyncRequest struct {
	value *IngestSyncRequest
	isSet bool
}

func (v NullableIngestSyncRequest) Get() *IngestSyncRequest {
	return v.value
}

func (v *NullableIngestSyncRequest) Set(val *IngestSyncRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestSyncRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestSyncRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestSyncRequest(val *IngestSyncRequest) *NullableIngestSyncRequest {
	return &NullableIngestSyncRequest{value: val, isSet: true}
}

func (v NullableIngestSyncRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestSyncRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


