/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefenseSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefenseSummary{}

// DefenseSummary Summary of RAGDefender behavior for response.
type DefenseSummary struct {
	Applied bool `json:"applied"`
	Success bool `json:"success"`
	Error NullableString `json:"error"`
	RemovedIndices []int32 `json:"removed_indices"`
	RiskScores []float32 `json:"risk_scores"`
	ProcessingTimeMs float32 `json:"processing_time_ms"`
}

type _DefenseSummary DefenseSummary

// NewDefenseSummary instantiates a new DefenseSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefenseSummary(applied bool, success bool, error_ NullableString, removedIndices []int32, riskScores []float32, processingTimeMs float32) *DefenseSummary {
	this := DefenseSummary{}
	this.Applied = applied
	this.Success = success
	this.Error = error_
	this.RemovedIndices = removedIndices
	this.RiskScores = riskScores
	this.ProcessingTimeMs = processingTimeMs
	return &this
}

// NewDefenseSummaryWithDefaults instantiates a new DefenseSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefenseSummaryWithDefaults() *DefenseSummary {
	this := DefenseSummary{}
	return &this
}

// GetApplied returns the Applied field value
func (o *DefenseSummary) GetApplied() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Applied
}

// GetAppliedOk returns a tuple with the Applied field value
// and a boolean to check if the value has been set.
func (o *DefenseSummary) GetAppliedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Applied, true
}

// SetApplied sets field value
func (o *DefenseSummary) SetApplied(v bool) {
	o.Applied = v
}

// GetSuccess returns the Success field value
func (o *DefenseSummary) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *DefenseSummary) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *DefenseSummary) SetSuccess(v bool) {
	o.Success = v
}

// GetError returns the Error field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DefenseSummary) GetError() string {
	if o == nil || o.Error.Get() == nil {
		var ret string
		return ret
	}

	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefenseSummary) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// SetError sets field value
func (o *DefenseSummary) SetError(v string) {
	o.Error.Set(&v)
}

// GetRemovedIndices returns the RemovedIndices field value
func (o *DefenseSummary) GetRemovedIndices() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.RemovedIndices
}

// GetRemovedIndicesOk returns a tuple with the RemovedIndices field value
// and a boolean to check if the value has been set.
func (o *DefenseSummary) GetRemovedIndicesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemovedIndices, true
}

// SetRemovedIndices sets field value
func (o *DefenseSummary) SetRemovedIndices(v []int32) {
	o.RemovedIndices = v
}

// GetRiskScores returns the RiskScores field value
func (o *DefenseSummary) GetRiskScores() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.RiskScores
}

// GetRiskScoresOk returns a tuple with the RiskScores field value
// and a boolean to check if the value has been set.
func (o *DefenseSummary) GetRiskScoresOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskScores, true
}

// SetRiskScores sets field value
func (o *DefenseSummary) SetRiskScores(v []float32) {
	o.RiskScores = v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value
func (o *DefenseSummary) GetProcessingTimeMs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value
// and a boolean to check if the value has been set.
func (o *DefenseSummary) GetProcessingTimeMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingTimeMs, true
}

// SetProcessingTimeMs sets field value
func (o *DefenseSummary) SetProcessingTimeMs(v float32) {
	o.ProcessingTimeMs = v
}

func (o DefenseSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefenseSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applied"] = o.Applied
	toSerialize["success"] = o.Success
	toSerialize["error"] = o.Error.Get()
	toSerialize["removed_indices"] = o.RemovedIndices
	toSerialize["risk_scores"] = o.RiskScores
	toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	return toSerialize, nil
}

func (o *DefenseSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applied",
		"success",
		"error",
		"removed_indices",
		"risk_scores",
		"processing_time_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefenseSummary := _DefenseSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefenseSummary)

	if err != nil {
		return err
	}

	*o = DefenseSummary(varDefenseSummary)

	return err
}

type NullableDefenseSummary struct {
	value *DefenseSummary
	isSet bool
}

func (v NullableDefenseSummary) Get() *DefenseSummary {
	return v.value
}

func (v *NullableDefenseSummary) Set(val *DefenseSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDefenseSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDefenseSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefenseSummary(val *DefenseSummary) *NullableDefenseSummary {
	return &NullableDefenseSummary{value: val, isSet: true}
}

func (v NullableDefenseSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefenseSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


