/*
RAG Defender Unified Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_rag_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentScoreModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentScoreModel{}

// DocumentScoreModel Score information for a document.
type DocumentScoreModel struct {
	Index int32 `json:"index"`
	RiskScore float32 `json:"risk_score"`
	IsRemoved bool `json:"is_removed"`
	Reason NullableString `json:"reason,omitempty"`
}

type _DocumentScoreModel DocumentScoreModel

// NewDocumentScoreModel instantiates a new DocumentScoreModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentScoreModel(index int32, riskScore float32, isRemoved bool) *DocumentScoreModel {
	this := DocumentScoreModel{}
	this.Index = index
	this.RiskScore = riskScore
	this.IsRemoved = isRemoved
	return &this
}

// NewDocumentScoreModelWithDefaults instantiates a new DocumentScoreModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentScoreModelWithDefaults() *DocumentScoreModel {
	this := DocumentScoreModel{}
	return &this
}

// GetIndex returns the Index field value
func (o *DocumentScoreModel) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *DocumentScoreModel) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *DocumentScoreModel) SetIndex(v int32) {
	o.Index = v
}

// GetRiskScore returns the RiskScore field value
func (o *DocumentScoreModel) GetRiskScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field value
// and a boolean to check if the value has been set.
func (o *DocumentScoreModel) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskScore, true
}

// SetRiskScore sets field value
func (o *DocumentScoreModel) SetRiskScore(v float32) {
	o.RiskScore = v
}

// GetIsRemoved returns the IsRemoved field value
func (o *DocumentScoreModel) GetIsRemoved() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRemoved
}

// GetIsRemovedOk returns a tuple with the IsRemoved field value
// and a boolean to check if the value has been set.
func (o *DocumentScoreModel) GetIsRemovedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRemoved, true
}

// SetIsRemoved sets field value
func (o *DocumentScoreModel) SetIsRemoved(v bool) {
	o.IsRemoved = v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentScoreModel) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentScoreModel) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *DocumentScoreModel) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *DocumentScoreModel) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *DocumentScoreModel) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *DocumentScoreModel) UnsetReason() {
	o.Reason.Unset()
}

func (o DocumentScoreModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentScoreModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["risk_score"] = o.RiskScore
	toSerialize["is_removed"] = o.IsRemoved
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	return toSerialize, nil
}

func (o *DocumentScoreModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"risk_score",
		"is_removed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentScoreModel := _DocumentScoreModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentScoreModel)

	if err != nil {
		return err
	}

	*o = DocumentScoreModel(varDocumentScoreModel)

	return err
}

type NullableDocumentScoreModel struct {
	value *DocumentScoreModel
	isSet bool
}

func (v NullableDocumentScoreModel) Get() *DocumentScoreModel {
	return v.value
}

func (v *NullableDocumentScoreModel) Set(val *DocumentScoreModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentScoreModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentScoreModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentScoreModel(val *DocumentScoreModel) *NullableDocumentScoreModel {
	return &NullableDocumentScoreModel{value: val, isSet: true}
}

func (v NullableDocumentScoreModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentScoreModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


