/*
Enterprise Connection Adapter

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sami_firewall_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Job type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Job{}

// Job Represents a single signed URL processing job.  Attributes:     id: str                    Tracking ID for the job — used for logging and tracing.     signed_url (str):          Pre-signed URL to download input file.     file_name  (str):          File name with extension — used to detect                                file type when URL has no extension.     file_size  (Optional[int]):File size in bytes — used for logging only.     enhanced_privacy_mode (bool): Flag to indicate if enhanced privacy mode is enabled for this job.
type Job struct {
	Id string `json:"id"`
	SignedUrl string `json:"signed_url"`
	FileName string `json:"file_name"`
	PolicyPacks []string `json:"policy_packs"`
	FileSize NullableInt32 `json:"file_size,omitempty"`
	EnhancedPrivacyMode *bool `json:"enhanced_privacy_mode,omitempty"`
}

type _Job Job

// NewJob instantiates a new Job object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJob(id string, signedUrl string, fileName string, policyPacks []string) *Job {
	this := Job{}
	this.Id = id
	this.SignedUrl = signedUrl
	this.FileName = fileName
	this.PolicyPacks = policyPacks
	var enhancedPrivacyMode bool = false
	this.EnhancedPrivacyMode = &enhancedPrivacyMode
	return &this
}

// NewJobWithDefaults instantiates a new Job object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobWithDefaults() *Job {
	this := Job{}
	var enhancedPrivacyMode bool = false
	this.EnhancedPrivacyMode = &enhancedPrivacyMode
	return &this
}

// GetId returns the Id field value
func (o *Job) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Job) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Job) SetId(v string) {
	o.Id = v
}

// GetSignedUrl returns the SignedUrl field value
func (o *Job) GetSignedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedUrl
}

// GetSignedUrlOk returns a tuple with the SignedUrl field value
// and a boolean to check if the value has been set.
func (o *Job) GetSignedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedUrl, true
}

// SetSignedUrl sets field value
func (o *Job) SetSignedUrl(v string) {
	o.SignedUrl = v
}

// GetFileName returns the FileName field value
func (o *Job) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *Job) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *Job) SetFileName(v string) {
	o.FileName = v
}

// GetPolicyPacks returns the PolicyPacks field value
func (o *Job) GetPolicyPacks() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PolicyPacks
}

// GetPolicyPacksOk returns a tuple with the PolicyPacks field value
// and a boolean to check if the value has been set.
func (o *Job) GetPolicyPacksOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyPacks, true
}

// SetPolicyPacks sets field value
func (o *Job) SetPolicyPacks(v []string) {
	o.PolicyPacks = v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize.Get()) {
		var ret int32
		return ret
	}
	return *o.FileSize.Get()
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetFileSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileSize.Get(), o.FileSize.IsSet()
}

// HasFileSize returns a boolean if a field has been set.
func (o *Job) HasFileSize() bool {
	if o != nil && o.FileSize.IsSet() {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given NullableInt32 and assigns it to the FileSize field.
func (o *Job) SetFileSize(v int32) {
	o.FileSize.Set(&v)
}
// SetFileSizeNil sets the value for FileSize to be an explicit nil
func (o *Job) SetFileSizeNil() {
	o.FileSize.Set(nil)
}

// UnsetFileSize ensures that no value is present for FileSize, not even an explicit nil
func (o *Job) UnsetFileSize() {
	o.FileSize.Unset()
}

// GetEnhancedPrivacyMode returns the EnhancedPrivacyMode field value if set, zero value otherwise.
func (o *Job) GetEnhancedPrivacyMode() bool {
	if o == nil || IsNil(o.EnhancedPrivacyMode) {
		var ret bool
		return ret
	}
	return *o.EnhancedPrivacyMode
}

// GetEnhancedPrivacyModeOk returns a tuple with the EnhancedPrivacyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetEnhancedPrivacyModeOk() (*bool, bool) {
	if o == nil || IsNil(o.EnhancedPrivacyMode) {
		return nil, false
	}
	return o.EnhancedPrivacyMode, true
}

// HasEnhancedPrivacyMode returns a boolean if a field has been set.
func (o *Job) HasEnhancedPrivacyMode() bool {
	if o != nil && !IsNil(o.EnhancedPrivacyMode) {
		return true
	}

	return false
}

// SetEnhancedPrivacyMode gets a reference to the given bool and assigns it to the EnhancedPrivacyMode field.
func (o *Job) SetEnhancedPrivacyMode(v bool) {
	o.EnhancedPrivacyMode = &v
}

func (o Job) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Job) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["signed_url"] = o.SignedUrl
	toSerialize["file_name"] = o.FileName
	toSerialize["policy_packs"] = o.PolicyPacks
	if o.FileSize.IsSet() {
		toSerialize["file_size"] = o.FileSize.Get()
	}
	if !IsNil(o.EnhancedPrivacyMode) {
		toSerialize["enhanced_privacy_mode"] = o.EnhancedPrivacyMode
	}
	return toSerialize, nil
}

func (o *Job) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"signed_url",
		"file_name",
		"policy_packs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJob := _Job{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJob)

	if err != nil {
		return err
	}

	*o = Job(varJob)

	return err
}

type NullableJob struct {
	value *Job
	isSet bool
}

func (v NullableJob) Get() *Job {
	return v.value
}

func (v *NullableJob) Set(val *Job) {
	v.value = val
	v.isSet = true
}

func (v NullableJob) IsSet() bool {
	return v.isSet
}

func (v *NullableJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJob(val *Job) *NullableJob {
	return &NullableJob{value: val, isSet: true}
}

func (v NullableJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


